"""user Contry details added in users table

Revision ID: b04cd740af4e
Revises: 68e0b88c258b
Create Date: 2024-08-12 18:56:14.734088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b04cd740af4e'
down_revision: Union[str, None] = '68e0b88c258b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
